name: Github CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: bioinfo
          python-version: 3.12
          channels: conda-forge,bioconda
          conda-remove-defaults: true

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -y samtools minimap2 bcftools freebayes htslib hapcut2 
          pip install --upgrade pip
          pip install biopython pysam jupyter nbconvert
          
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Week 5 & 6
        shell: bash -l {0}
        run: 
          conda activate bioinfo
          jupyter nbconvert --to notebook --execute week5/week5.ipynb --output week5.ipynb --ExecutePreprocessor.kernel_name=python3
      - uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: week5/week5.ipynb

